Repository ResultadosDigitais/rdstation-ruby-client, pull requests merged in 2019-04, with the labels that each got.

#31 V2 client
  .rspec
  Gemfile.lock
  lib/rdstation-ruby-client.rb
  lib/rdstation/authorization_header.rb
  lib/rdstation/client.rb
  lib/rdstation/contacts.rb
  lib/rdstation/error.rb
  lib/rdstation/events.rb
  lib/rdstation/fields.rb
  lib/rdstation/version.rb
  lib/rdstation/webhooks.rb
  rdstation-ruby-client.gemspec
  spec/lib/rdstation/authorization_header_spec.rb
  spec/lib/rdstation/client_spec.rb
  spec/lib/rdstation/contacts_spec.rb
  spec/lib/rdstation/events_spec.rb
  spec/lib/rdstation/fields_spec.rb
  spec/lib/rdstation/webhooks_spec.rb
Labels: 2.0, Review me, enhancement

#35 Update issue templates
  .github/ISSUE_TEMPLATE/rdsm-ruby-client-issue-template.md
Labels: enhancement

#38 Improve errors structure
  lib/rdstation/api_response.rb
  lib/rdstation/error.rb
  lib/rdstation/error_handler.rb
  lib/rdstation/error_handler/bad_request.rb
  lib/rdstation/error_handler/default.rb
  lib/rdstation/error_handler/resource_not_found.rb
  lib/rdstation/error_handler/unauthorized.rb
  lib/rdstation/events.rb
  lib/rdstation/webhooks.rb
  spec/lib/rdstation/contacts_spec.rb
  spec/lib/rdstation/error_handler/default_spec.rb
  spec/lib/rdstation/error_handler/resource_not_found_spec.rb
  spec/lib/rdstation/error_handler/unauthorized_spec.rb
  spec/lib/rdstation/error_handler_spec.rb
  spec/lib/rdstation/webhooks_spec.rb
Labels: 2.0, WIP

#42 V2 changelog and migration guide
  CHANGELOG.md
  README.md
Labels: 2.0, WIP

#43 Remove deprecated error attributes
  lib/rdstation/error.rb
Labels: 2.0, [Effort] Low, techdebt

#40 Release 2.0
  .rspec
  CHANGELOG.md
  README.md
  lib/rdstation-ruby-client.rb
  lib/rdstation/api_response.rb
  lib/rdstation/authorization_header.rb
  lib/rdstation/client.rb
  lib/rdstation/contacts.rb
  lib/rdstation/error.rb
  lib/rdstation/error_handler.rb
  lib/rdstation/error_handler/bad_request.rb
  lib/rdstation/error_handler/default.rb
  lib/rdstation/error_handler/resource_not_found.rb
  lib/rdstation/error_handler/unauthorized.rb
  lib/rdstation/events.rb
  lib/rdstation/fields.rb
  lib/rdstation/version.rb
  lib/rdstation/webhooks.rb
  rdstation-ruby-client.gemspec
  spec/lib/rdstation-ruby-client_spec.rb
  spec/lib/rdstation/authorization_header_spec.rb
  spec/lib/rdstation/client_spec.rb
  spec/lib/rdstation/contacts_spec.rb
  spec/lib/rdstation/error_handler/default_spec.rb
  spec/lib/rdstation/error_handler/resource_not_found_spec.rb
  spec/lib/rdstation/error_handler/unauthorized_spec.rb
  spec/lib/rdstation/error_handler_spec.rb
  spec/lib/rdstation/events_spec.rb
  spec/lib/rdstation/fields_spec.rb
  spec/lib/rdstation/webhooks_spec.rb
Labels: 2.0
